### ISSUE TITLE
Codec based token embedder.

### ISSUE THREAD

**Issue by faroit** [lucidrains/audiolm-pytorch#1]
@lucidrains i think a reimplemenation will be quite hard to kick off without access to a good neural codec model. Google likely won't open source soundstream but maybe one could use a https://github.com/google/lyra for now and focus on speech instead of fullband audio/music

**Comment by faroit** [comment]
also tagging @wesbz: can you give a quick status on https://github.com/wesbz/SoundStream? Would it be usable already?

**Comment by lucidrains** [comment]
@faroit no worries, i'll just build the whole thing. i have the residual quantization (hardest part of sound stream) already built at https://github.com/lucidrains/vector-quantize-pytorch/blob/master/vector_quantize_pytorch/residual_vq.py

**Comment by wesbz** [comment]
Hey @faroit , thanks for tagging me and for your interest. As I started a PhD program a few months ago, I couldn't find time to address the issues raised on my work on the SoundStream paper.
Please consider my repo as an incomplete example/tutorial and feel free to fork it to adjust your need until I manage to find time to allocate to this. Lucidrains is quite right, and the next hardest thing after the residual quantization is managing the losses in an efficient way.

**Comment by faroit** [comment]
@lucidrains @wesbz https://github.com/google/lyra/releases/tag/v1.2.0
