### ISSUE TITLE
Residual connection after decoder attention?

### ISSUE THREAD

**Issue by alexdemartos** [lucidrains/audiolm-pytorch#104]
In the `decode_from_codebook_indices` method there is a residual connection after the decoder attention:

https://github.com/lucidrains/audiolm-pytorch/blob/d244a6c90b33627bad1e38ae2e20e821e6818253/audiolm_pytorch/soundstream.py#L494

Which is not present in the `forward` method: 

https://github.com/lucidrains/audiolm-pytorch/blob/d244a6c90b33627bad1e38ae2e20e821e6818253/audiolm_pytorch/soundstream.py#L567

Is this correct?

In my case, I found significantly higher audio quality during inference after removing this residual connection (matching training conditions).

**Comment by lucidrains** [comment]
@alexdemartos oh gosh yes :man_facepalming: thank you for catching this

https://github.com/lucidrains/audiolm-pytorch/commit/e8ee51f1efb5bb1bba26ec691191763dbece0ecc

**Comment by lucidrains** [comment]
@alexdemartos does this mean you have already gotten to sampling from the coarse and fine transformers stages?

**Comment by cyanbx** [comment]
thanks for detecting this bug! It helps me a lot

**Comment by lucidrains** [comment]
ok, i'm guessing he's slinking back off into the darkness to pen his next paper :laughing: 

i'll leave him be
