### ISSUE TITLE
SoundStream and Transformer num units

### ISSUE THREAD

**Issue by LWprogramming** [lucidrains/audiolm-pytorch#110]
Currently [SoundStream has](https://github.com/lucidrains/audiolm-pytorch/blob/main/audiolm_pytorch/soundstream.py#L355)         `rq_num_quantizers = 8`-- should this be 12 instead or is there something about the bitrate that's different from how the paper handles things?

Also, should Transformer have [16 heads instead of 8](https://github.com/lucidrains/audiolm-pytorch/blob/main/audiolm_pytorch/audiolm_pytorch.py#L453) by default? 

(based on what I read in the original paper :) )

**Comment by lucidrains** [comment]
@LWprogramming does `MusicLM` use a `Soundstream` with greater number of quantizers?

**Comment by LWprogramming** [comment]
Ah yeah, `SoundStream` in `MusicLM` is also 12 quantizers (page 4, left column, 3rd paragraph [here](https://arxiv.org/pdf/2301.11325.pdf))

**Comment by lucidrains** [comment]
@LWprogramming nice! have it as a default on `MusicLMSoundStream` https://github.com/lucidrains/audiolm-pytorch/blob/main/audiolm_pytorch/soundstream.py#L733

**Comment by LWprogramming** [comment]
Hmm, looking at the [`AudioLMSoundStream` right next to it](https://github.com/lucidrains/audiolm-pytorch/blob/main/audiolm_pytorch/soundstream.py#L719), shouldn't `rq_num_quantizers` also be 12 there? My understanding is that the number of quantizers affects bitrate for the embeddings specifically but is unrelated to `target_sample_hz`, so we don't reduce quantizers there (also, if this is incorrect, then the default SoundStream implementation should have [`rq_num_quantizers`](https://github.com/lucidrains/audiolm-pytorch/blob/9b8e702feacb603fe5cead3ce0d8e6610c24b8ab/audiolm_pytorch/soundstream.py#L355) and [`target_sample_hz`](https://github.com/lucidrains/audiolm-pytorch/blob/9b8e702feacb603fe5cead3ce0d8e6610c24b8ab/audiolm_pytorch/soundstream.py#L371) compatible right?)

**Comment by lucidrains** [comment]
@LWprogramming i'm not sure actually; did you see 12 in the Audio LM paper?

**Comment by LWprogramming** [comment]
I just re-skimmed the soundstream paper and it seems like they tested various arrangements of quantizers, but AudioLM says specifically 12 ([page 6, left column, 2nd paragraph](https://arxiv.org/pdf/2209.03143.pdf))

**Comment by sohananisetty** [comment]
The original Soundstream paper has 8 quantizers. The formula to determine the number of quantizers is:

$$N_q = r/(log_2 N)$$

Where $N_q$ is the number of quantizers, r is the number of bits for each output frame, and N is codebook size. With sampling rate = 24Khz, bitrate = 6Kbps, strides (3,4,5,8) we get r = 120 and $N_q = 12$ (This implementation). With strides = (2,4,5,8) we get r = 80 and $N_q = 8$ (The Soundstream paper).

**Comment by lucidrains** [comment]
@sohananisetty @LWprogramming ok, thank you both for looking up these details!

i've decided to default to 8 quantizers, as well as the (2, 4, 5, 8) with 16khz for the soundstream paper

but i have also fixed `AudioLMSoundStream` to have 12 quantizers
