### ISSUE TITLE
can soundstream be trained with fp16？

### ISSUE THREAD

**Issue by Liujingxiu23** [lucidrains/audiolm-pytorch#127]
run:
 accelerate launch --multi_gpu --mixed_precision=fp16 --gpu_ids=0,1 train.py

error info
Input type (CUDAComplexHalfType) and weight type (CUDAComplexFloatType) should be the same

relative code:
def forward(self, x):
    weight, bias = map(torch.view_as_complex, (self.weight, self.bias))
    return F.conv2d(x, weight, bias, stride = self.stride, padding = self.padding)

**Comment by lucidrains** [comment]
@Liujingxiu23 this complex valued discriminator is going to be the end of me lol

so i believe the complex network needs to be done at full precision - i think i'll just force an autocast here. will get it done later today

**Comment by Liujingxiu23** [comment]
@lucidrains Thank you！It works. And my trainning which not use fp16 have trained several days， and the synthesized wave is just nearly to understand.  


And another problem I meet and ask for help:
I use codec from Encodec to use a FineTransformer, so I need to change the dataloader to return (coarse_code, fine_code) which are extracted and saved as numpy, and revised some of the code to train the model.
The question is I can not trainning the model with multi-GPUs.

The key error info is(batchsize=64):
RuntimeError: The size of tensor a (64) must match the size of tensor b (0) at non-singleton dimension 2

And  part of my code is:

**Comment by lucidrains** [comment]
hmm let's move this to discussion, as the original issue has been solved

**Comment by Liujingxiu23** [comment]
the loss run to nan after 1000 steps as the loss was logged the first time.

**Comment by stevenhillis** [comment]
Seconding training soundstream with mixed precision as an outstanding issue on 0.25.5. I see real values for all losses except for multi_spectral_recon_loss, which is inf at step 0 and quickly moves to nan.
