### ISSUE TITLE
Add .eval when exporting flac

### ISSUE THREAD

**Issue by yygle** [lucidrains/audiolm-pytorch#132]
@lucidrains Thanks for the awesome work. You may forgot to add `.eval()` when exporting the flac files in soundstream trainer. And it may cause differences for the output wavs.

**Comment by lucidrains** [comment]
@yygle oh, wasn't that done [here](https://github.com/lucidrains/audiolm-pytorch/blob/main/audiolm_pytorch/trainer.py#L460)? or are you referring to somewhere else?

**Comment by yygle** [comment]
sorry, my mistake. It use different names, `self.soundstream` and `self.model`.

**Comment by lucidrains** [comment]
@yygle yea, there is an EMA version

no worries, thanks for raising the issue!
