### ISSUE TITLE
semantic transformer training

### ISSUE THREAD

**Issue by syjunghwang** [lucidrains/audiolm-pytorch#154]
When I learn Semantic Transformer, I see the code that make the semantic embedding a random value and train this embedding. I need to get the semantic token ID value from Hubert, but taking the embedding value corresponding to token from pre-trained Hubert is not correct. right?

**Comment by lucidrains** [comment]
@syjunghwang yea, that is not correct

**Comment by stg1205** [comment]
why don't take the embedding from pretrained Hubert?
