### ISSUE TITLE
coarsetransformer has wrong code? 

### ISSUE THREAD

**Issue by syjunghwang** [lucidrains/audiolm-pytorch#155]
we can get [batchsize, encodec quantizer number, timesteps] from encodec, and I think that the codes related to cuting encoec output down to the number of coarse quantizers(=3) should be changed from " coarse_token_ids, _ = indices[..., :num_coarse_quantizers], indices[...,num_coarse_quantizers:]
" to 
    coarse_token_ids, _ = indices[..., :num_coarse_quantizers, :], indices[...,num_coarse_quantizers:,:]
, am I mistaken?

**Comment by syjunghwang** [comment]
At the soundstream code you mentioned, it's set to (batchsize, timestep, quantizers(=8)) instead of (batchsize, quantizers(=8), timestep), so I think we can change the Output like the soundstream in the encoder python code.

**Comment by LWprogramming** [comment]
Wait a minute, I think I figured out the mistake. The original Soundstream [code](https://github.com/lucidrains/audiolm-pytorch/blob/9f2d153272c6eac6c200fc482827b70242c46403/audiolm_pytorch/soundstream.py#L669) is correct-- the problem I had was that `x` is reshaped to `batch x codebook size x timesteps` but crucially `indices` is still `batch x num_frames x num_quantizers` and each frame corresponds to a single set of ids (one for each quantizer). So I think the Soundstream code is compatible with the coarse transformer code and the error is in my Encodec implementation.
