### ISSUE TITLE
Bug? mask = True

### ISSUE THREAD

**Issue by maitycyrus** [lucidrains/audiolm-pytorch#164]
https://github.com/lucidrains/audiolm-pytorch/blob/e2579052a7ae9036b32aaf817e12f7f7be14ebf4/audiolm_pytorch/hubert_kmeans.py#L82

shouldn't mask be set to False since default value is True?

**Comment by lucidrains** [comment]
also, as an aside, fairseq code has gotten so much better than i last remembered it being a few years ago! actually quite readable!
