### ISSUE TITLE
Confusion about the coarse transformer trainer

### ISSUE THREAD

**Issue by xtluo** [lucidrains/audiolm-pytorch#167]
https://github.com/lucidrains/audiolm-pytorch/blob/241bae318f3e49860e765058c0c7abeceb1c9760/audiolm_pytorch/audiolm_pytorch.py#L1414

@lucidrains Here at line 1414 and 1415, why not:

```
batch = raw_wave_for_codec.shape[0]
num_timesteps = raw_wave_for_codec.shape[1]
```

**Comment by lucidrains** [comment]
@xtluo Thanks Xiaotao! https://github.com/lucidrains/audiolm-pytorch/commit/914ba79adbde1af937b8bb8e29e17e7b2e295dc2

**Comment by xtluo** [comment]
Thank you for your email.This is  an automatic reply, which means I have received your email and I will check it as soon as possible.Best wishes !Xiaotao Luo
