### ISSUE TITLE
Potentially useful pretrained models

### ISSUE THREAD

**Issue by gkucsko** [lucidrains/audiolm-pytorch#169]
Hey friends, we recently release some text-to-audio models that are very similar to the great work you all are doing here. Maybe some of them can be used as a starting point for finetuning within this repo (esp semantic and coarse/fine).
https://github.com/suno-ai/bark

**Comment by lucidrains** [comment]
@gkucsko nice results! this confirms that Encodec + AudioLM scheme should work well together

feel free to repost this to discussions, as this is not an issue

**Comment by gkucsko** [comment]
good point, thanks for all the work here!
