### ISSUE TITLE
can not install audiolm-pytorch

### ISSUE THREAD

**Issue by linlongrd** [lucidrains/audiolm-pytorch#182]
pip install audiolm-pytorch
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 2
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by SloMoShun** [comment]
I also get this issue:

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scikit-learn
Failed to build scikit-learn
ERROR: Could not build wheels for scikit-learn, which is required to install pyproject.toml-based projects

**Comment by rsxdalv** [comment]
you can do `pip install audiolm-pytorch==1.1.4`

**Comment by SloMoShun** [comment]
> you can do `pip install audiolm-pytorch==1.1.4`

Thank you this worked!

**Comment by lucidrains** [comment]
should be ok now
