### ISSUE TITLE
question about the semantic process

### ISSUE THREAD

**Issue by asr-pub** [lucidrains/audiolm-pytorch#186]
https://github.com/lucidrains/audiolm-pytorch/blob/9ec98366e1c376088f44269f10c615b1ec640b09/audiolm_pytorch/audiolm_pytorch.py#L143-L145C5

Hello, Why removing adjacent duplicate elements ?

**Comment by lucidrains** [comment]
this was actually recommended by @eonglints , who follows the field closely

**Comment by lucidrains** [comment]
@asr-pub maybe the durations should be preserved on a separate dimension for the network (like run-length encoding?) i'm actually confused myself why it is standard practice to do this

**Comment by asr-pub** [comment]
> @asr-pub maybe the durations should be preserved on a separate dimension for the network (like run-length encoding?) i'm actually confused myself why it is standard practice to do this

Thank you for replying
