### ISSUE TITLE
Poor audio quality

### ISSUE THREAD

**Issue by cpdu** [lucidrains/audiolm-pytorch#191]
Hi,

Thank you so much for sharing the codes. We try to train an AudioLM model on LibriTTS but we find it has a poor quality and is much worse than the official demos.

Do you have any comments on that? I'm wondering that have you ever achieved a similar quality to the official demos in your training?

**Comment by lucidrains** [comment]
@cpdu normally i would dig into it, but i've already received multiple reports of people training successfully (in discussions as well as through my email)

if you need help with the training, recommend opening up a discussion if someone is charitable enough to handhold you through it
