### ISSUE TITLE
Batch size > 1 in generate function

### ISSUE THREAD

**Issue by eonglints** [lucidrains/audiolm-pytorch#20]
Hey, the line [`last_logits = rearrange(last_logits, 'b 1 c -> b c')`](https://github.com/lucidrains/audiolm-pytorch/blob/06eecbdb640c7a84aa6aad1041b179f9167a6a5c/audiolm_pytorch/audiolm_pytorch.py#L822) in the `SemanticTransformer` `generate()` function, understandably doesn't like a batch size greater than 1. Is there a nice clean fix for this that doesn't involve doing things like `prime_ids = prime_ids[:1, :]` earlier in the function? FWIW I don't neccessarily think it's a bad thing to only do one generation rather than a whole batch.

**Comment by eonglints** [comment]
Sorry, I think you might have fixed this [here](https://github.com/lucidrains/audiolm-pytorch/commit/dfd4b8030c64370a80972c36f6d2b8d1b9c263f4). Will test and re-open if required.

**Comment by lucidrains** [comment]
@eonglints yes indeed! had a pretty bad bug before :cry:
