### ISSUE TITLE
hi. If i want to train text to Chinese speech audiolm , what confuse me is that pretrained hubert model is English-style, Does it affect my Chinese version training? Or i have to re-train hubert with my own large chinese dataset ? Appreciate !!!! @lucidrains 

### ISSUE THREAD

**Issue by hyhzl** [lucidrains/audiolm-pytorch#219]

**Comment by glide-the** [comment]
This should be the most accurate answer you can get

https://github.com/lucidrains/audiolm-pytorch/issues/80#issuecomment-1432293079

**Comment by hyhzl** [comment]
> This should be the most accurate answer you can get
> 
> [#80 (comment)](https://github.com/lucidrains/audiolm-pytorch/issues/80#issuecomment-1432293079)

what? i had read hubert 、wav2vec 2.0 etc.

**Comment by hyhzl** [comment]
https://huggingface.co/TencentGameMate/chinese-hubert-large/tree/main

**Comment by lucidrains** [comment]
@hyhzl can you bring this to the discussions?
