### ISSUE TITLE
Inconsistent samples for multiple targets in SoundDataset

### ISSUE THREAD

**Issue by ilya16** [lucidrains/audiolm-pytorch#224]
When audio lengths are greater than `max_length` and multiple target sample rates are used, the `SoundDataset` samples audios with different start positions:
https://github.com/lucidrains/audiolm-pytorch/blob/c65bb97662a1ef29ec6359d25bf4022c2cb82a27/audiolm_pytorch/data.py#L86-L97

Affects the training data for `CoarseTransformer`.

**Comment by lucidrains** [comment]
@ilya16 yes indeed that does not seem right :disappointed: 

decided to take the strategy of doing all the resampling + curtail / pad on the highest target sample freq first, before resampling to all the rest of the target sample freqs

want to see if that addresses the issue?

**Comment by ilya16** [comment]
@lucidrains looks good!
