### ISSUE TITLE
bandwidth params not work!

### ISSUE THREAD

**Issue by wotulong** [lucidrains/audiolm-pytorch#225]
I want to imrove the audio quality by setting bandwidth params like [encodec](https://github.com/facebookresearch/encodec), but when i set bandwidth param of EncodecWrapper, it doesn't work, my code is bellow:
```
audio, codes, _ = codec(raw_audio, return_encoded=True, bandwidth=12.0)
```
It seems that the bandwidth params in some fun has been setted as a constant value 6.
Because i want to synthesis singing voice, so the quality of audio is very important to me.
How can i to set the params to improve the audio quality, anyone can help me, thanks!

**Comment by lucidrains** [comment]
ahh i see, so are you training the coarse transformer then?

**Comment by lucidrains** [comment]
@wotulong want to see if 1.2.29 does it?

**Comment by lucidrains** [comment]
you can pass in the `bandwidth` when initting `EncodecWrapper`
