### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by amrzv** [lucidrains/audiolm-pytorch#226]
Hi.
When running `HubertWithKmeans` the Assertion error is raised because `scikit-learn` doesn't match required version `0.24.0`
<img width="700" alt="image" src="https://github.com/lucidrains/audiolm-pytorch/assets/36787333/fb9de1c0-254e-44a7-aef4-9b672e1b04c2">

Looks like `scikit-learn==0.24.0` should be specified in [setup.py](https://github.com/lucidrains/audiolm-pytorch/blob/main/setup.py#L31)

P.S: tested in [colab](https://colab.research.google.com/github/lucidrains/audiolm-pytorch/blob/main/audiolm_pytorch_demo.ipynb).
P.S.S: current version in colab is `scikit-learn==1.2.2`.

**Comment by lucidrains** [comment]
@amrzv i ran into some weird error last time and was too lazy to figure it out

could you just try running the command as per the assert instructions?

**Comment by lucidrains** [comment]
iirc, i'm not even using scikit learn anymore. the cluster centers are extracted [here](https://github.com/lucidrains/audiolm-pytorch/blob/main/audiolm_pytorch/hubert_kmeans.py#L66)

**Comment by lucidrains** [comment]
@amrzv yea let me know if it works with the manual pip install

we can leave this issue open, as i'd like to just suppress the warning in the fairseq library, and just extract the cluster centers and use them. if anyone is training their own set of cluster centers, they can deal with that scikit-learn version problem

**Comment by lucidrains** [comment]
removed the assert altogether
