### ISSUE TITLE
Likely beartype package breakage

### ISSUE THREAD

**Issue by rsxdalv** [lucidrains/audiolm-pytorch#231]
Edit: Since this project relies on PyTorch, having problems is a near 100%. The workaround is to pin beartype==0.15.0.

I'm a downstream project and users have reported beartype's update from 0.15 to 0.16 as breaking the application (Mac, Windows and Linux) and I have reproduced it.

I haven't verified if audiolm breaks on its own but I think it's not unlikely.

**Comment by lucidrains** [comment]
@rsxdalv oh darn! looks like pytorch will need to fix something on their end too

pinned to 0.15.0 for now, thanks!
