### ISSUE TITLE
How to create wav2vec checkpoints?

### ISSUE THREAD

**Issue by djqualia** [lucidrains/audiolm-pytorch#25]
First off, thanks for this code!  I've been trying to test it out, and am attempting to start training the semantic transformer.  Following the current instructions, it's not clear how I should create the files referenced in the wav2vec checkpoint/kmeans paths, e.g:

wav2vec = HubertWithKmeans(
    checkpoint_path = './hubert/hubert_base_ls960.pt',
    kmeans_path = './hubert/hubert_base_ls960_L9_km500.bin'
)

How did you create these?  Thanks again!

**Comment by djqualia** [comment]
Do I need to create these files using fairseq? https://github.com/facebookresearch/fairseq/tree/main/examples/hubert

**Comment by lucidrains** [comment]
@djqualia oh yup! exactly

added some comments https://github.com/lucidrains/audiolm-pytorch/commit/039ec88b075369879c83cffe90625df2612e30a4

**Comment by lucidrains** [comment]
@djqualia do you want to try 0.1.2 and see if the error message is more helpful?

**Comment by djqualia** [comment]
Sure!  I updated to the latest and get the same error, but here's a bit more of it:

  File "/mnt/c/audio-ml-workspace/audiolm/audiolm_pytorch/audiolm_pytorch.py", line 829, in __init__
    assert self.wav2vec.codebook_size == transformer.num_semantic_tokens, f'num_semantic_tokens on SemanticTransformer must be set to {self.wav2vec.codebook_size}'
  File "/home/qualia/anaconda3/envs/audiolm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1265, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'FairseqVQWav2Vec' object has no attribute 'codebook_size'

It seems that even if I download the "vq-wav2vec.pt" from the link above and reference that (even though it's not what I want), I get the same error.

The setup code looks like:

wav2vec = FairseqVQWav2Vec(
    checkpoint_path = '/mnt/c/models/audiolm/semantic/vq-wav2vec.pt',
    target_sample_hz = 44100,
)

semantic_transformer = SemanticTransformer(
    num_semantic_tokens = 500,
    dim = 1024,
    depth = 6
).cuda()

trainer = SemanticTransformerTrainer(
    transformer = semantic_transformer,
    wav2vec = wav2vec,
    folder = '/mnt/d/audio_input/bass_training',
    results_folder = '/mnt/c/models/audiolm/semantic',
    batch_size = 1,
    data_max_length = 882000, # 20s
    num_train_steps = 1
)

The error happens on the line for "trainer = SemanticTransformerTrainer(...)"

HTH!  I'm happy to do any more testing, as I'm very excited about this project :-)

**Comment by lucidrains** [comment]
@djqualia oh that is strange, how about 0.1.5?

the one i'm using is

```bash
$ wget https://dl.fbaipublicfiles.com/fairseq/wav2vec/vq-wav2vec_kmeans.pt
```

**Comment by lucidrains** [comment]
@djqualia  oh yup, you must be using the gumbel one

try using the kmeans clustered embeddings version

**Comment by djqualia** [comment]
Yes, that worked.  Thanks!
