### ISSUE TITLE
Cannot retrieve dependency version for gateloop-transformer>=0.5.2, possible regression?

### ISSUE THREAD

**Issue by afreemanio** [lucidrains/audiolm-pytorch#262]
When trying to install this package, I get:
ERROR: Could not find a version that satisfies the requirement gateloop-transformer>=0.5.2 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.10, 0.0.11, 0.0.12, 0.0.14, 0.0.15, 0.0.16, 0.0.18, 0.0.19, 0.0.20, 0.0.21, 0.0.22, 0.0.23, 0.0.24, 0.0.25, 0.0.26, 0.1.0, 0.1.1, 0.1.2, 0.1.4, 0.1.5, 0.2.0, 0.2.1, 0.2.2, 0.2.3)
ERROR: No matching distribution found for gateloop-transformer>=0.5.2

Seems to be introduced in this commit:
https://github.com/lucidrains/audiolm-pytorch/commit/c4fb6f6ba1717d84654de9141f3742409e2bcc48

Is there something I'm missing? On PyPi (https://pypi.org/project/audiolm-pytorch/) it also does not list 0.5.2 as a version.

**Comment by lucidrains** [comment]
@afreemanio my bad! should be fixed
