### ISSUE TITLE
Heads up that ComplexFloat doesn't appear to be supported by DistributedDataParallel (NCCL backend)

### ISSUE THREAD

**Issue by eonglints** [lucidrains/audiolm-pytorch#31]
SoundStream training seems to be working well on a single GPU but when you attempt to use more than one GPU, this error is thrown up: `RuntimeError: Input tensor data type is not supported for NCCL process group: ComplexFloat`.

It would appear that the [`ComplexLeakyReLU`](https://github.com/lucidrains/audiolm-pytorch/blob/aa053305de671c8e4e0ac5494370ad8e2e640ff0/audiolm_pytorch/soundstream.py#L99) class is probably the cause, but the workaround mentioned [here](https://github.com/pytorch/pytorch/issues/71613#issuecomment-1034448731) doesn't neccessarily seem to be a great answer.

Not really a bug for AudioLM, just a heads up for anyone attempting multi-GPU training right now.

(Pytorch 1.13)

**Comment by lucidrains** [comment]
@eonglints thanks for reporting this! i'll try to debug this later this week

for now, i addressed something that was bothering me, and switched over to the modrelu that seems to be popular in the complex valued neural network field

**Comment by lucidrains** [comment]
@eonglints ahh i see, Meta just concatted the real and imaginary and treated it as a 2d feature map https://github.com/facebookresearch/encodec/blob/3837f0db2a3b0fa00084cdd145cc6e8553048431/encodec/msstftd.py#L89 they are also applying weight norm on the convs

ok yea, let's plan on doing this and see if this fixes the issue

**Comment by lucidrains** [comment]
they aren't doing anything fancy like modrelu, just leakyrelu on both real and imag

**Comment by eonglints** [comment]
Awesome, thanks, will do.

**Comment by lucidrains** [comment]
this pytorch issue looks pretty hopeless for being resolved any time soon

i think what i'll do is just manually handle the real and imaginary values as was done in this repository https://github.com/litcoderr/ComplexCNN i'm a big noob when it comes to complex valued networks though, so let me know if i'm not on the right track!

**Comment by lucidrains** [comment]
@eonglints success! i think?

if anyone is running accelerate with DDP, can you verify that setting [this](https://github.com/lucidrains/audiolm-pytorch/blob/main/audiolm_pytorch/soundstream.py#L465) to `False` works just as well as single machine left `True`? i can then cleanup and just use the simulate complex discriminator (and that flag is going as well)

**Comment by lucidrains** [comment]
going to preemptively close this, feel free to reopen if it is still an issue

**Comment by eonglints** [comment]
Sure thing, I'll give it a try on Monday and let you know how I get on. Thanks!

**Comment by eonglints** [comment]
Unfortunately I ran into a different issue when trying this on Monday so wasn't able to verify. However, [this note](https://github.com/facebookresearch/encodec/issues/16#issuecomment-1318883767) from one of the Encodec researchers (in the context of multi-GPU training) is interesting: "we actually did not use DDP for the training but custom distributed routines."

Unsure if it's related, just flagging in case.

**Comment by lucidrains** [comment]
@eonglints that's really good to know! thanks for sharing that :pray:

**Comment by lucidrains** [comment]
@eonglints i'll try to (yet) again resolve this today, i'm sure i can get the simulated complex working

**Comment by lucidrains** [comment]
still not fixed, according to @djqualia  :cry:

**Comment by lucidrains** [comment]
ok, tried to figure out what the workaround was that they proposed in the pytorch thread, and it turns out to be what i was doing anyways

i'll have to step through the complex and the complex-as-real network and make sure all the values and gradients are the same. thankfully there's a lot of open sourced projects to look at as a guide

**Comment by zhvng** [comment]
heads up @lucidrains I get an error when running the newest version of the code:

```
Traceback (most recent call last):                                                                                                                                                                                               
  File ".../train_soundstream.py", line 24, in <module>                                                                                                                                              
    trainer.train()                                                                                                                                                                                                              
  File ".../audiolm-pytorch/audiolm_pytorch/trainer.py", line 418, in train                                                                                                                                        
    logs = self.train_step()                                                                                                                                                                                                     
  File ".../audiolm-pytorch/audiolm_pytorch/trainer.py", line 337, in train_step                                                                                                                                   
    discr_losses = self.soundstream(                                                                                                                                                                                             
  File ".../env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl                                                                                                   
    return forward_call(*input, **kwargs)                                                                                                                                                                                        
  File ".../audiolm-pytorch/audiolm_pytorch/soundstream.py", line 651, in forward                                                                                                                                  
    stft_discr_loss = hinge_discr_loss(stft_fake_logits, stft_real_logits)        
File "...audiolm_pytorch/soundstream.py", line 42, in hinge_discr_loss
    return (F.relu(1 + fake) + F.relu(1 - real)).mean()
  File ".../env/lib/python3.10/site-packages/torch/nn/functional.py", line 1457, in relu
    result = torch.relu(input)
RuntimeError: clamp is not supported for complex types
```

tried to fix this by passing in abs(stft_fake_logits) and abs(stft_real_logits) into `hinge_discr_loss` [here](https://github.com/lucidrains/audiolm-pytorch/blob/main/audiolm_pytorch/soundstream.py#L651) but i get a very high loss (~10^7)

```
20: soundstream total loss: 13529093.125, soundstream recon loss: 0.076 | discr (scale 1) loss: 3.104 | discr (scale 0.5) loss: 2.482 | discr (scale 0.25) loss: 2.575
21: soundstream total loss: 11155972.625, soundstream recon loss: 0.072 | discr (scale 1) loss: 3.264 | discr (scale 0.5) loss: 2.181 | discr (scale 0.25) loss: 2.203
22: soundstream total loss: 14122796.625, soundstream recon loss: 0.081 | discr (scale 1) loss: 3.616 | discr (scale 0.5) loss: 1.932 | discr (scale 0.25) loss: 2.035
```

**Comment by djqualia** [comment]
which version are you using?  i've trained with 0.11.1 the past ~24h and its working well for me.  i haven't been able to try the newer versions yet (but will test them later...)

**Comment by lucidrains** [comment]
@zhvng @djqualia ohh crap, i broke it sorry :sweat:  fixed! :crossed_fingers:

**Comment by lucidrains** [comment]
@zhvng the high loss is actually coming from the new ["multi spectral recon loss"](https://github.com/lucidrains/audiolm-pytorch/commit/47871901f7a1d5aaed0800ddd14fb1c7933b0f5c) which wasn't present in previous version

**Comment by djqualia** [comment]
just started training on 0.11.6 -- FYI it started with the following warning 4x:

  warnings.warn(
/home/qualia/anaconda3/envs/audiolm/lib/python3.8/site-packages/torchaudio/functional/functional.py:571: UserWarning: At least one mel filterbank has all zero values. The value for `n_mels` (64) may be set too high. Or, the value for `n_freqs` (65) may be set too low.

**Comment by lucidrains** [comment]
@djqualia i have no clue what i'm doing [lol](https://github.com/lucidrains/audiolm-pytorch/commit/6123c770fe4e42b8b3cc131aa135ea8b06677d5a)

**Comment by zhvng** [comment]
hmm 64 is normal for `n_mels` but not sure what they by `n_freq`, looking into it right now

**Comment by djqualia** [comment]
restarted on 0.11.8, got less warnings but still see:

/home/qualia/anaconda3/envs/audiolm/lib/python3.8/site-packages/torchaudio/functional/functional.py:571: UserWarning: At least one mel filterbank has all zero values. The value for `n_mels` (32) may be set too high. Or, the value for `n_freqs` (129) may be set too low.
  warnings.warn(
/home/qualia/anaconda3/envs/audiolm/lib/python3.8/site-packages/torchaudio/functional/functional.py:571: UserWarning: At least one mel filterbank has all zero values. The value for `n_mels` (64) may be set too high. Or, the value for `n_freqs` (257) may be set too low.
  warnings.warn(

the training still proceeds normally otherwise...

**Comment by lucidrains** [comment]
@djqualia ohh thanks for reporting! i've decided to make the hyperparameters i'm uncertain about [fully configurable](https://github.com/lucidrains/audiolm-pytorch/commit/923763595717675be6fce5b9a4fbe224ca05416a#diff-7e2ef88e24ccc344bf6eeeefc84a9daf25616a49d07c7bfd0473b3e039909de4R458)

you can set the individual `n_fft` and `n_mels` by passing in a tuple, for each window size

**Comment by lucidrains** [comment]
also, after some back and forth on the pytorch thread, i was able to get the [proposed workaround](https://github.com/lucidrains/audiolm-pytorch/commit/f308c90a4444505eff91ab969cd0149a0e069ced#diff-7e2ef88e24ccc344bf6eeeefc84a9daf25616a49d07c7bfd0473b3e039909de4R133) running for complex conv2d

going to close this issue... inb4 @djqualia tells me it stopped converging again haha

**Comment by turian** [comment]
"the high loss is actually coming from the new ["multi spectral recon loss"](https://github.com/lucidrains/audiolm-pytorch/commit/47871901f7a1d5aaed0800ddd14fb1c7933b0f5c) which wasn't present in previous version, added in 0.11.2 . Just made it so you can turn it off by setting the multi spectral recon loss weight to 0"

@lucidrains another reason for a loss balancer ? #60 

[Schaffer et al 2022](https://arxiv.org/pdf/2208.12387.pdf) train a GAN and include a poor-mans (non-EMA) loss balancer too: "To find suitable loss
weights for all 3 types of losses on the generator (LSGAN
loss, deep matching loss, and multi-scale spectral loss; see
Section 3), we solved a least squares equation to weigh all
loss terms equally for the first 1k training iterations. After
that, we froze those weights applied to the losses for the
remainder of training"

**Comment by lucidrains** [comment]
@turian yes indeed, i was thinking about that last night! will definitely prioritize it

**Comment by lucidrains** [comment]
@turian but, alas, time for meetings rest of the week and little coding :cry:

**Comment by lucidrains** [comment]
@turian agreed, i really like it! i've seen this type of adaptive loss weighting in other works too, but a lot less elegant

**Comment by lucidrains** [comment]
oh just noticed the GAN paper has some hacky non-ema solution, i like the encodec one much better

**Comment by turian** [comment]
@lucidrains well they're both GAN papers to be fair. Seems like they are here to stay. I foresee upcoming commentators complaining about GAN collapse issues and it being a bit fiddly to fix, but that's what the community is for.
