### ISSUE TITLE
About the Coarse and Fine acoustic modeling

### ISSUE THREAD

**Issue by yangdongchao** [lucidrains/audiolm-pytorch#36]
Hi, I try to using your code to reproduce AudioLM.  I found that your  CoarseTransformer model is based on self-attention. In the AudioLM paper, they assert ". During training, we use random cropping to equivalent input lengths of 30, 10 and 3 seconds for the three stages". Considering their soundstream is 320 downsample, which means that 1s audio including 50 tokens. 10s audio inlcudes 500 tokens for one codebook, and soundstream inlcudes more than 4 codebook. I want to know whether CoarseTransformer  can deal with such long sequence?  Do you have any idea to solve the long sequence problem?

**Comment by eonglints** [comment]
It's a good question. Obviously the compute required for Transformers doesn't scale nicely with sequence length but I would just try and train a model with the maximum sequence length your compute budget can allow and see how you get on. @lucidrains has already implemented a bunch of Transformer models that are more efficient on long sequences but it would appear that most folks are sticking with fairly vanilla architectures for audio language models right now. It's definitely something that should be investigated though.

**Comment by djqualia** [comment]
FWIW, I was able to lower data_max_length when training fine transformers (after initially running into an OOM), and still proceed to generate samples later on.  So I think to some degree you can accomplish this already by adjusting data_max_length in each training stage (i.e. it does not need to be fixed).

**Comment by lucidrains** [comment]
i don't have the most optimal sampling code, but can code it up once people have something trained

the repository now has the best length extrapolation positional embeddings fwiw

**Comment by lucidrains** [comment]
i don't have the most optimal sampling code, but can code it up once people have something trained

the repository now has the best length extrapolation positional embeddings
