### ISSUE TITLE
About training Soundstream from checkpoint

### ISSUE THREAD

**Issue by BlackFox1197** [lucidrains/audiolm-pytorch#41]
When trying to train Soundstream from a saved checkpoint, it seems to work well (in an test case the checkpoint after 9000 steps is loaded) until it saves the model. The saved model behaves like learning from the start. 
When trying to learn like only 10 steps, the model (not saved to disk) seems to work like the 9000 model.

**Comment by lucidrains** [comment]
@BlackFox1197 ahh yea it is probably because i'm not saving the optimizer states

will fix it this week, thanks for bringing this up!

**Comment by lucidrains** [comment]
@BlackFox1197 added a `.save(path)` and `.load(path)` on the `SoundstreamTrainer` that should resolve this issue! https://github.com/lucidrains/audiolm-pytorch/commit/89a350025f94e8e8c68f9a846778234b2a580fbe

**Comment by LWprogramming** [comment]
Hi, is `.save` supposed to be called [here](https://github.com/lucidrains/audiolm-pytorch/blob/daeedb2798fed2275a8d6a67ecf150fdf2396dbc/audiolm_pytorch/trainer.py#L401) and likewise for the other `Trainer`s? Or are you calling the functions outside (?) of the train loop and saving state to some other folder periodically?

**Comment by gblue1223** [comment]
> Hi, is `.save` supposed to be called [here](https://github.com/lucidrains/audiolm-pytorch/blob/daeedb2798fed2275a8d6a67ecf150fdf2396dbc/audiolm_pytorch/trainer.py#L401) and likewise for the other `Trainer`s? Or are you calling the functions outside (?) of the train loop and saving state to some other folder periodically?

I agree, `save` and `load` function should placed in `train_step`. It is confusing for first-timers.
