### ISSUE TITLE
Special reason for this single kernel to be 3?

### ISSUE THREAD

**Issue by inspirit** [lucidrains/audiolm-pytorch#59]
Is there any special reason why this only kernel=3? seems like copy paste :)
https://github.com/lucidrains/audiolm-pytorch/blob/d8d5798773edc2edba9d92d293039db893bd234b/audiolm_pytorch/soundstream.py#L347

**Comment by lucidrains** [comment]
![Screenshot from 2023-01-20 13-05-53](https://user-images.githubusercontent.com/108653/213805186-54e1fd8a-1042-4f8c-8292-e371c2104b51.png)

thanks for reviewing the architecture :smiley: 

it looks like i followed their diagram, and if you look at the bottom, they have `k=3` for some reason

**Comment by inspirit** [comment]
i see, once again referring to Encodec they seem to keep it simple:
input/output kernels = 7, residual kernel=3, and strangely enough they have only 1 residual unit inside encoder block

**Comment by lucidrains** [comment]
the details probably don't matter all that much

biggest conceptual leap is the residual quantization, and i squeezed in local attention (and just now a learned multi-headed EMA), which should both improve it even more

**Comment by lucidrains** [comment]
regardless, thanks for looking everything over! 🙏
