### ISSUE TITLE
I can't make it work

### ISSUE THREAD

**Issue by olainid** [lucidrains/audiolm-pytorch#72]
First of all thank you for your work.

I am trying to get the code to work. I get the system to train, using about 5190 hours of speech (a part of the libri-light) but at the output of the generation I only have noise. I have tried to encode-decode an audio signal with the SoundStream model that I obtained as the result of the training and I see that it is not working because there is only noise at the output.

Could you tell me if I'm doing something wrong? Maybe I need to use a larger amount of audio or a specific database?

Thank you!

**Comment by lucidrains** [comment]
@olainid you should join Laion and collaborate with other trainers

i can't help you with training through the issues. there's too many things that could be going wrong, especially if you are not a deep learning practitioner by trade

**Comment by lucidrains** [comment]
@olainid @eonglints has already gotten some early results with semantic transformer, so i am pretty confident that at the very least, soundstream and semantic transformer are working https://github.com/lucidrains/audiolm-pytorch/discussions/24
