### ISSUE TITLE
multi-scale spectral reconstruction loss

### ISSUE THREAD

**Issue by AndreyBocharnikov** [lucidrains/audiolm-pytorch#76]
Hello and thank you for your excellent job, your implementations are really helpful. 

I've got a question about losses in soundstream model, in the original [paper](https://arxiv.org/pdf/2107.03312.pdf), formulas (4) and (5) on page 6 correspond to the multi-scale spectral reconstruction loss, but I don't see it in your implementation. As far as I can tell, generator losses are presented [here](https://github.com/lucidrains/audiolm-pytorch/blob/main/audiolm_pytorch/soundstream.py#L557) and there is no one that I'm talking about. Maybe I just missed it.

**Comment by lucidrains** [comment]
@AndreyBocharnikov Hey Andrey

I believe that is taken care of https://github.com/lucidrains/audiolm-pytorch/blob/main/audiolm_pytorch/soundstream.py#L587, but do let me know if I am mistakened

**Comment by AndreyBocharnikov** [comment]
I think because you compute the loss between intermediate representations of the discriminator of real generated waves, it is a feature matching loss for the discriminator in frequency domain. It is formula (3) in the paper and this loss should be computed for both frequency-discriminator and wave-discriminator, as you do in your implementation. But mel-spectrogram representations are not the same as intermediate representations of the discriminator, and they are being computed in formulas (4) and (5) as it is stated a bit below those formulas.

**Comment by lucidrains** [comment]
@AndreyBocharnikov yes, i do believe you are right! thank you for pointing this out

i will start a PR on this tomorrow morning. would you be open to doing a code review of the final implementation (i am not that familiar with the audio domain and its various representations)

**Comment by lucidrains** [comment]
@AndreyBocharnikov hey Andrey, decided to take a wild stab at this loss [here](https://github.com/lucidrains/audiolm-pytorch/commit/933a8a59cf33dd9a6b91b90727809107cfaab006)

let me know if that looks ok to you. for all you audiophiles out there, would appreciate a code review :pray:

**Comment by AndreyBocharnikov** [comment]
Left some comments on that commit

**Comment by lucidrains** [comment]
@AndreyBocharnikov this is so so helpful, thank you Andrey! :pray:
