### ISSUE TITLE
ComplexConv2d in ComplexSTFTDiscriminator gives RuntimeError

### ISSUE THREAD

**Issue by lg-lg** [lucidrains/audiolm-pytorch#83]
Hi,
I am trying to train a soundstream model, and I get the following error during the forward pass:

File "audiolm-pytorch/audiolm-pytorch/soundstream.py", line 148, in forward
    return F.conv2d(x, weight, bias, stride = self.stride, padding = self.padding)
RuntimeError: getCudnnDataTypeFromScalarType() not supported for ComplexFloat

It seems that conv2d not support the complex results obtained by STFT in ComplexSTFTDiscriminator. Has anyone come across the same issue before?

**Comment by Rongjiehuang** [comment]
Yes, it seems that the new update commitment causes this issue.

**Comment by lucidrains** [comment]
aw, [this issue](https://github.com/lucidrains/audiolm-pytorch/issues/31) is going to be the end of me, haha

which version of pytorch are you on? it seems to be working for me

**Comment by Rongjiehuang** [comment]
I am on 1.10.0
sounds good, I will try your version

**Comment by lucidrains** [comment]
@Rongjiehuang ok! do let me know if it works or not, in which case, i'll just [update the dependencies](https://github.com/lucidrains/audiolm-pytorch/blob/main/setup.py#L31)

**Comment by lucidrains** [comment]
@Rongjiehuang ahh ok, yes, i believe it is only available in 1.12, let me update the dependencies

**Comment by lucidrains** [comment]
should be resolved, feel free to reopen if not

**Comment by Rongjiehuang** [comment]
yes, I try and it works in 1.12, thanks!

**Comment by Darius-H** [comment]
I tried with torch=1.13.1 and it doesn't work, it seems only work with torch=1.12

**Comment by haydenshively** [comment]
This is broken again in torch 2.0.1 (using `accelerate launch my_train_file.py` and a vanilla FSDP config)

```
audiolm_pytorch/soundstream.py", line 194, in forward
    weight, bias = map(torch.view_as_complex, (self.weight, self.bias))
RuntimeError: Tensor must have a storage_offset divisible by 2
```

Also tried reverting to the plain `nn.Conv2d(..., dtype=torch.complex64)` version, but that fails in accelerate's `prepare` step:

```
ValueError: Integer parameters are unsupported
```

So for now I think the only way to use FSDP is to `view_as_real` on the STFT before passing it into the discriminator, like [this old repo](https://github.com/wesbz/SoundStream).
