### ISSUE TITLE
Can you please implement 'SingSong' by Google?

### ISSUE THREAD

**Issue by adamfils2** [lucidrains/audiolm-pytorch#87]
SingSong generates backing instruments from input vocals.
https://arxiv.org/abs/2301.12662v1
https://paperswithcode.com/paper/singsong-generating-musical-accompaniments
Demo:
https://storage.googleapis.com/sing-song/index.html

In the paper they use audiolm.

Could you please provide code to train this?
I would really appreciate it.
Thanks

**Comment by lucidrains** [comment]
Yea sure, closing because this is same as https://github.com/lucidrains/audiolm-pytorch/issues/86

**Comment by mishav78** [comment]
did someone code the singsong implementation?

**Comment by lucidrains** [comment]
no i never got around to this

**Comment by mishav78** [comment]
I will email you
