### ISSUE TITLE
soundstream.load() no longer works in 0.12.3

### ISSUE THREAD

**Issue by djqualia** [lucidrains/audiolm-pytorch#89]
is this intentional?

my first guess is that we should be calling the associated trainer.load() instead.  however, when it comes to inference time, does that mean we need to load all the trainer classes?

in case it helps, the exception i got when trying to resume training on 0.12.3 (started on 0.12.1):

  File "train_soundstream.py", line 6, in <module>
    soundstream = config_util.createSoundStream(config)
  File "/home/qualia/code/audiolm/config_util.py", line 38, in createSoundStream
    soundstream.load(checkpoint)
  File "/home/qualia/code/audiolm/audiolm_pytorch/soundstream.py", line 499, in load
    self.load_state_dict(torch.load(str(path)))
  File "/home/qualia/anaconda3/envs/audiolm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SoundStream:
	Missing key(s) in state_dict: "encoder.0.conv.weight", "encoder.0.conv.bias", "encoder.1.0.fn.0.conv.weight", "encoder.1.0.fn.0.conv.bias", "encoder.1.0.fn.2.conv.weight", "encoder.1.0.fn.2.conv.bias", "encoder.1.1.fn.0.conv.weight", "encoder.1.1.fn.0.conv.bias", "encoder.1.1.fn.2.conv.weight", "encoder.1.1.fn.2.conv.bias", "encoder.1.2.fn.0.conv.weight", "encoder.1.2.fn.0.conv.bias", "encoder.1.2.fn.2.conv.weight", "encoder.1.2.fn.2.conv.bias", "encoder.1.3.conv.weight", "encoder.1.3.conv.bias", "encoder.2.prenorm.weight", "encoder.2.prenorm.bias", "encoder.2.mhema.expansion", "encoder.2.mhema.reduction", "encoder.2.mhema.alphas", "encoder.2.mhema.dampen_factors", "encoder.3.0.fn.0.conv.weight", "encoder.3.0.fn.0.conv.bias", "encoder.3.0.fn.2.conv.weight", "encoder.3.0.fn.2.conv.bias", "encoder.3.1.fn.0.conv.weight", "encoder.3.1.fn.0.conv.bias", "encoder.3.1.fn.2.conv.weight", "encoder.3.1.fn.2.conv.bias", "encoder.3.2.fn.0.conv.weight", "encoder.3.2.fn.0.conv.bias", "encoder.3.2.fn.2.conv.weight", "encoder.3.2.fn.2.conv.bias", "encoder.3.3.conv.weight", "encoder.3.3.conv.bias", "encoder.4.prenorm.weight", "encoder.4.prenorm.bias", "encoder.4.mhema.expansion", "encoder.4.mhema.reduction", "encoder.4.mhema.alphas", "encoder.4.mhema.dampen_factors", "encoder.5.0.fn.0.conv.weight", "encoder.5.0.fn.0.conv.bias", "encoder.5.0.fn.2.conv.weight", "encoder.5.0.fn.2.conv.bias", "encoder.5.1.fn.0.conv.weight", "encoder.5.1.fn.0.conv.bias", "encoder.5.1.fn.2.conv.weight", "encoder.5.1.fn.2.conv.bias", "encoder.5.2.fn.0.conv.weight", "encoder.5.2.fn.0.conv.bias", "encoder.5.2.fn.2.conv.weight", "encoder.5.2.fn.2.conv.bias", "encoder.5.3.conv.weight", "encoder.5.3.conv.bias", "encoder.6.prenorm.weight", "encoder.6.prenorm.bias", "encoder.6.mhema.expansion", "encoder.6.mhema.reduction", "encoder.6.mhema.alphas", "encoder.6.mhema.dampen_factors", "encoder.7.0.fn.0.conv.weight", "encoder.7.0.fn.0.conv.bias", "encoder.7.0.fn.2.conv.weight", "encoder.7.0.fn.2.conv.bias", "encoder.7.1.fn.0.conv.weight", "encoder.7.1.fn.0.conv.bias", "encoder.7.1.fn.2.conv.weight", "encoder.7.1.fn.2.conv.bias", "encoder.7.2.fn.0.conv.weight", "encoder.7.2.fn.0.conv.bias", "encoder.7.2.fn.2.conv.weight", "encoder.7.2.fn.2.conv.bias", "encoder.7.3.conv.weight", "encoder.7.3.conv.bias", "encoder.8.prenorm.weight", "encoder.8.prenorm.bias", "encoder.8.mhema.expansion", "encoder.8.mhema.reduction", "encoder.8.mhema.alphas", "encoder.8.mhema.dampen_factors", "encoder.9.conv.weight", "encoder.9.conv.bias", "encoder_attn.0.attn.q_scale", "encoder_attn.0.attn.k_scale", "encoder_attn.0.attn.norm.weight", "encoder_attn.0.attn.norm.bias", "encoder_attn.0.attn.to_qkv.weight", "encoder_attn.0.attn.attn_fn.rel_pos.inv_freq", "encoder_attn.0.attn.to_out.weight", "encoder_attn.0.ff.0.weight", "encoder_attn.0.ff.0.bias", "encoder_attn.0.ff.1.weight", "encoder_attn.0.ff.4.weight", "encoder_attn.1.attn.q_scale", "encoder_attn.1.attn.k_scale", "encoder_attn.1.attn.norm.weight", "encoder_attn.1.attn.norm.bias", "encoder_attn.1.attn.to_qkv.weight", "encoder_attn.1.attn.attn_fn.rel_pos.inv_freq", "encoder_attn.1.attn.to_out.weight", "encoder_attn.1.ff.0.weight", "encoder_attn.1.ff.0.bias", "encoder_attn.1.ff.1.weight", "encoder_attn.1.ff.4.weight", "rq.layers.0._codebook.initted", "rq.layers.0._codebook.cluster_size", "rq.layers.0._codebook.embed_avg", "rq.layers.0._codebook.embed", "rq.layers.1._codebook.initted", "rq.layers.1._codebook.cluster_size", "rq.layers.1._codebook.embed_avg", "rq.layers.1._codebook.embed", "rq.layers.2._codebook.initted", "rq.layers.2._codebook.cluster_size", "rq.layers.2._codebook.embed_avg", "rq.layers.2._codebook.embed", "rq.layers.3._codebook.initted", "rq.layers.3._codebook.cluster_size", "rq.layers.3._codebook.embed_avg", "rq.layers.3._codebook.embed", "rq.layers.4._codebook.initted", "rq.layers.4._codebook.cluster_size", "rq.layers.4._codebook.embed_avg", "rq.layers.4._codebook.embed", "rq.layers.5._codebook.initted", "rq.layers.5._codebook.cluster_size", "rq.layers.5._codebook.embed_avg", "rq.layers.5._codebook.embed", "rq.layers.6._codebook.initted", "rq.layers.6._codebook.cluster_size", "rq.layers.6._codebook.embed_avg", "rq.layers.6._codebook.embed", "rq.layers.7._codebook.initted", "rq.layers.7._codebook.cluster_size", "rq.layers.7._codebook.embed_avg", "rq.layers.7._codebook.embed", "rq.layers.8._codebook.initted", "rq.layers.8._codebook.cluster_size", "rq.layers.8._codebook.embed_avg", "rq.layers.8._codebook.embed", "rq.layers.9._codebook.initted", "rq.layers.9._codebook.cluster_size", "rq.layers.9._codebook.embed_avg", "rq.layers.9._codebook.embed", "rq.layers.10._codebook.initted", "rq.layers.10._codebook.cluster_size", "rq.layers.10._codebook.embed_avg", "rq.layers.10._codebook.embed", "rq.layers.11._codebook.initted", "rq.layers.11._codebook.cluster_size", "rq.layers.11._codebook.embed_avg", "rq.layers.11._codebook.embed", "decoder_attn.0.attn.q_scale", "decoder_attn.0.attn.k_scale", "decoder_attn.0.attn.norm.weight", "decoder_attn.0.attn.norm.bias", "decoder_attn.0.attn.to_qkv.weight", "decoder_attn.0.attn.attn_fn.rel_pos.inv_freq", "decoder_attn.0.attn.to_out.weight", "decoder_attn.0.ff.0.weight", "decoder_attn.0.ff.0.bias", "decoder_attn.0.ff.1.weight", "decoder_attn.0.ff.4.weight", "decoder_attn.1.attn.q_scale", "decoder_attn.1.attn.k_scale", "decoder_attn.1.attn.norm.weight", "decoder_attn.1.attn.norm.bias", "decoder_attn.1.attn.to_qkv.weight", "decoder_attn.1.attn.attn_fn.rel_pos.inv_freq", "decoder_attn.1.attn.to_out.weight", "decoder_attn.1.ff.0.weight", "decoder_attn.1.ff.0.bias", "decoder_attn.1.ff.1.weight", "decoder_attn.1.ff.4.weight", "decoder.0.conv.weight", "decoder.0.conv.bias", "decoder.1.0.conv.weight", "decoder.1.0.conv.bias", "decoder.1.1.fn.0.conv.weight", "decoder.1.1.fn.0.conv.bias", "decoder.1.1.fn.2.conv.weight", "decoder.1.1.fn.2.conv.bias", "decoder.1.2.fn.0.conv.weight", "decoder.1.2.fn.0.conv.bias", "decoder.1.2.fn.2.conv.weight", "decoder.1.2.fn.2.conv.bias", "decoder.1.3.fn.0.conv.weight", "decoder.1.3.fn.0.conv.bias", "decoder.1.3.fn.2.conv.weight", "decoder.1.3.fn.2.conv.bias", "decoder.2.prenorm.weight", "decoder.2.prenorm.bias", "decoder.2.mhema.expansion", "decoder.2.mhema.reduction", "decoder.2.mhema.alphas", "decoder.2.mhema.dampen_factors", "decoder.3.0.conv.weight", "decoder.3.0.conv.bias", "decoder.3.1.fn.0.conv.weight", "decoder.3.1.fn.0.conv.bias", "decoder.3.1.fn.2.conv.weight", "decoder.3.1.fn.2.conv.bias", "decoder.3.2.fn.0.conv.weight", "decoder.3.2.fn.0.conv.bias", "decoder.3.2.fn.2.conv.weight", "decoder.3.2.fn.2.conv.bias", "decoder.3.3.fn.0.conv.weight", "decoder.3.3.fn.0.conv.bias", "decoder.3.3.fn.2.conv.weight", "decoder.3.3.fn.2.conv.bias", "decoder.4.prenorm.weight", "decoder.4.prenorm.bias", "decoder.4.mhema.expansion", "decoder.4.mhema.reduction", "decoder.4.mhema.alphas", "decoder.4.mhema.dampen_factors", "decoder.5.0.conv.weight", "decoder.5.0.conv.bias", "decoder.5.1.fn.0.conv.weight", "decoder.5.1.fn.0.conv.bias", "decoder.5.1.fn.2.conv.weight", "decoder.5.1.fn.2.conv.bias", "decoder.5.2.fn.0.conv.weight", "decoder.5.2.fn.0.conv.bias", "decoder.5.2.fn.2.conv.weight", "decoder.5.2.fn.2.conv.bias", "decoder.5.3.fn.0.conv.weight", "decoder.5.3.fn.0.conv.bias", "decoder.5.3.fn.2.conv.weight", "decoder.5.3.fn.2.conv.bias", "decoder.6.prenorm.weight", "decoder.6.prenorm.bias", "decoder.6.mhema.expansion", "decoder.6.mhema.reduction", "decoder.6.mhema.alphas", "decoder.6.mhema.dampen_factors", "decoder.7.0.conv.weight", "decoder.7.0.conv.bias", "decoder.7.1.fn.0.conv.weight", "decoder.7.1.fn.0.conv.bias", "decoder.7.1.fn.2.conv.weight", "decoder.7.1.fn.2.conv.bias", "decoder.7.2.fn.0.conv.weight", "decoder.7.2.fn.0.conv.bias", "decoder.7.2.fn.2.conv.weight", "decoder.7.2.fn.2.conv.bias", "decoder.7.3.fn.0.conv.weight", "decoder.7.3.fn.0.conv.bias", "decoder.7.3.fn.2.conv.weight", "decoder.7.3.fn.2.conv.bias", "decoder.8.prenorm.weight", "decoder.8.prenorm.bias", "decoder.8.mhema.expansion", "decoder.8.mhema.reduction", "decoder.8.mhema.alphas", "decoder.8.mhema.dampen_factors", "decoder.9.conv.weight", "decoder.9.conv.bias", "discriminators.0.init_conv.weight", "discriminators.0.init_conv.bias", "discriminators.0.conv_layers.0.0.weight", "discriminators.0.conv_layers.0.0.bias", "discriminators.0.conv_layers.1.0.weight", "discriminators.0.conv_layers.1.0.bias", "discriminators.0.conv_layers.2.0.weight", "discriminators.0.conv_layers.2.0.bias", "discriminators.0.conv_layers.3.0.weight", "discriminators.0.conv_layers.3.0.bias", "discriminators.0.final_conv.0.weight", "discriminators.0.final_conv.0.bias", "discriminators.0.final_conv.2.weight", "discriminators.0.final_conv.2.bias", "discriminators.1.init_conv.weight", "discriminators.1.init_conv.bias", "discriminators.1.conv_layers.0.0.weight", "discriminators.1.conv_layers.0.0.bias", "discriminators.1.conv_layers.1.0.weight", "discriminators.1.conv_layers.1.0.bias", "discriminators.1.conv_layers.2.0.weight", "discriminators.1.conv_layers.2.0.bias", "discriminators.1.conv_layers.3.0.weight", "discriminators.1.conv_layers.3.0.bias", "discriminators.1.final_conv.0.weight", "discriminators.1.final_conv.0.bias", "discriminators.1.final_conv.2.weight", "discriminators.1.final_conv.2.bias", "discriminators.2.init_conv.weight", "discriminators.2.init_conv.bias", "discriminators.2.conv_layers.0.0.weight", "discriminators.2.conv_layers.0.0.bias", "discriminators.2.conv_layers.1.0.weight", "discriminators.2.conv_layers.1.0.bias", "discriminators.2.conv_layers.2.0.weight", "discriminators.2.conv_layers.2.0.bias", "discriminators.2.conv_layers.3.0.weight", "discriminators.2.conv_layers.3.0.bias", "discriminators.2.final_conv.0.weight", "discriminators.2.final_conv.0.bias", "discriminators.2.final_conv.2.weight", "discriminators.2.final_conv.2.bias", "stft_discriminator.init_conv.weight", "stft_discriminator.init_conv.bias", "stft_discriminator.layers.0.0.weight", "stft_discriminator.layers.0.0.bias", "stft_discriminator.layers.0.1.b", "stft_discriminator.layers.0.2.weight", "stft_discriminator.layers.0.2.bias", "stft_discriminator.layers.1.0.weight", "stft_discriminator.layers.1.0.bias", "stft_discriminator.layers.1.1.b", "stft_discriminator.layers.1.2.weight", "stft_discriminator.layers.1.2.bias", "stft_discriminator.layers.2.0.weight", "stft_discriminator.layers.2.0.bias", "stft_discriminator.layers.2.1.b", "stft_discriminator.layers.2.2.weight", "stft_discriminator.layers.2.2.bias", "stft_discriminator.layers.3.0.weight", "stft_discriminator.layers.3.0.bias", "stft_discriminator.layers.3.1.b", "stft_discriminator.layers.3.2.weight", "stft_discriminator.layers.3.2.bias", "stft_discriminator.layers.4.0.weight", "stft_discriminator.layers.4.0.bias", "stft_discriminator.layers.4.1.b", "stft_discriminator.layers.4.2.weight", "stft_discriminator.layers.4.2.bias", "stft_discriminator.layers.5.0.weight", "stft_discriminator.layers.5.0.bias", "stft_discriminator.layers.5.1.b", "stft_discriminator.layers.5.2.weight", "stft_discriminator.layers.5.2.bias", "stft_discriminator.final_conv.weight", "stft_discriminator.final_conv.bias", "mel_spec_transforms.0.spectrogram.window", "mel_spec_transforms.0.mel_scale.fb", "mel_spec_transforms.1.spectrogram.window", "mel_spec_transforms.1.mel_scale.fb", "mel_spec_transforms.2.spectrogram.window", "mel_spec_transforms.2.mel_scale.fb", "mel_spec_transforms.3.spectrogram.window", "mel_spec_transforms.3.mel_scale.fb", "mel_spec_transforms.4.spectrogram.window", "mel_spec_transforms.4.mel_scale.fb", "mel_spec_transforms.5.spectrogram.window", "mel_spec_transforms.5.mel_scale.fb". 
	Unexpected key(s) in state_dict: "model", "ema_model", "optim", "discr_optim", "multiscale_discr_optimizer_0", "multiscale_discr_optimizer_1", "multiscale_discr_optimizer_2".

**Comment by ZYW507** [comment]
got the same error while trying to train Coarse Transform, do you have any idea where this might go wrong?

**Comment by lucidrains** [comment]
@djqualia @ZYW507 oh hey! sorry i broke things

so i realized that i wasn't properly checkpointing the optimizer state, which is important for resuming training properly

i'll get around to fixing this today or tomorrow

**Comment by lucidrains** [comment]
@djqualia do you want to try this function in lieu of `.load` ? https://github.com/lucidrains/audiolm-pytorch/commit/13e9dc3b1b9bf78399eef6086571204d51e9db99#diff-7e2ef88e24ccc344bf6eeeefc84a9daf25616a49d07c7bfd0473b3e039909de4R501

**Comment by lucidrains** [comment]
@ZYW507 ohh, do you have a script and the error trace?

**Comment by ZYW507** [comment]
> @ZYW507 ohh, do you have a script and the error trace?

I think it is the same error message as above? Here it is: 

RuntimeError                              Traceback (most recent call last)
<ipython-input-23-204731cfb1aa> in <module>
      9 )
     10 
---> 11 soundstream.load(f"./{soundstream_ckpt}")
     12 
     13 coarse_transformer = CoarseTransformer(

1 frames
/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict)
   1669 
   1670         if len(error_msgs) > 0:
-> 1671             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
   1672                                self.__class__.__name__, "\n\t".join(error_msgs)))
   1673         return _IncompatibleKeys(missing_keys, unexpected_keys)

RuntimeError: Error(s) in loading state_dict for SoundStream:
	Missing key(s) in state_dict: "encoder.0.conv.weight", "encoder.0.conv.bias", "encoder.1.0.fn.0.conv.weight", "encoder.1.0.fn.0.conv.bias", "encoder.1.0.fn.2.conv.weight", "encoder.1.0.fn.2.conv.bias", "encoder.1.1.fn.0.conv.weight", "encoder.1.1.fn.0.conv.bias", "encoder.1.1.fn.2.conv.weight", "encoder.1.1.fn.2.conv.bias", "encoder.1.2.fn.0.conv.weight", "encoder.1.2.fn.0.conv.bias", "encoder.1.2.fn.2.conv.weight", "encoder.1.2.fn.2.conv.bias", "encoder.1.3.conv.weight", "encoder.1.3.conv.bias", "encoder.2.prenorm.weight", "encoder.2.prenorm.bias", "encoder.2.mhema.expansion", "encoder.2.mhema.reduction", "encoder.2.mhema.alphas", "encoder.2.mhema.dampen_factors", "encoder.3.0.fn.0.conv.weight", "encoder.3.0.fn.0.conv.bias", "encoder.3.0.fn.2.conv.weight", "encoder.3.0.fn.2.conv.bias", "encoder.3.1.fn.0.conv.weight", "encoder.3.1.fn.0.conv.bias", "encoder.3.1.fn.2.conv.weight", "encoder.3.1.fn.2.conv.bias", "encoder.3.2.fn.0.conv.weight", "encoder.3.2.fn.0.conv.bias", "encoder.3.2.fn.2.conv.weight", "encoder.3.2.fn.2.conv.bias", "encoder.3.3.conv.weight", "encoder.3.3.conv.bias", "encoder.4.prenorm.weight", "encoder.4.prenorm.bias", "encoder.4.mhema.expansion", "encoder.4.mhema.reduction", "encoder.4.mhema.alphas", "encoder.4.mhema.dampen_factors", "encoder.5.0.fn.0.conv.weight", "encoder.5.0.fn.0.conv.bias", "encoder.5.0.fn.2.conv.weight", "encoder.5.0.fn.2.conv.bias", "encoder.5.1.fn.0.conv.weight", "encoder.5.1.fn.0.conv.bias", "encoder.5.1.fn.2.conv.weight", "encoder...
	Unexpected key(s) in state_dict: "model", "ema_model", "optim", "discr_optim", "multiscale_discr_optimizer_0", "multiscale_discr_optimizer_1", "multiscale_discr_optimizer_2".

**Comment by lucidrains** [comment]
@ZYW507 try `soundstream.load_from_trainer_saved_obj(f"./{soundstream_ckpt}")`

**Comment by lucidrains** [comment]
should be fixed, feel free to reopen if not!
