### ISSUE TITLE
How to use multi-GPU training?   I can't use  CUDA_VISIBLE_DEVICES to implement multi-GPU

### ISSUE THREAD

**Issue by lzl1456** [lucidrains/audiolm-pytorch#90]

**Comment by lucidrains** [comment]
@lzl1456 you can use the accelerate library, which is integrated into each of the trainers

just added some instructions [here](https://github.com/lucidrains/audiolm-pytorch#multi-gpu)

**Comment by lzl1456** [comment]
thanks, but not working， Below is my measure


In which compute environment are you running?
This machine                                                                                                                                                                                           
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Which type of machine are you using?                                                                                                                                                                   
multi-GPU                                                                                                                                                                                              
How many different machines will you use (use more than 1 for multi-node training)? [1]:                                                                                                               
Do you wish to optimize your script with torch dynamo?[yes/NO]:n                                                                                                                                       
Please enter yes or no.                                                                                                                                                                                
Do you wish to optimize your script with torch dynamo?[yes/NO]:no                                                                                                                                      
Do you want to use DeepSpeed? [yes/NO]: no                                                                                                                                                             
Do you want to use FullyShardedDataParallel? [yes/NO]: no
Do you want to use Megatron-LM ? [yes/NO]: no
How many GPU(s) should be used for distributed training? [1]:2
What GPU(s) (by id) should be used for training on this machine as a comma-seperated list? [all]:
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Do you wish to use FP16 or BF16 (mixed precision)?
no  


Traceback (most recent call last):
  File "train_soundstream.py", line 23, in <module>
    trainer.train()
  File "/home/notebook/code/personal/80370039/lzl_musicml/lzl_code/audiolm_pytorch/trainer.py", line 416, in train
    logs = self.train_step()
  File "/home/notebook/code/personal/80370039/lzl_musicml/lzl_code/audiolm_pytorch/trainer.py", line 348, in train_step
Traceback (most recent call last):
  File "train_soundstream.py", line 23, in <module>
    self.accelerator.backward(discr_loss / self.grad_accum_every, retain_graph = True)
  File "/opt/conda/lib/python3.8/site-packages/accelerate-0.16.0-py3.8.egg/accelerate/accelerator.py", line 1441, in backward
    loss.backward(**kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch-1.13.1-py3.8-linux-x86_64.egg/torch/_tensor.py", line 488, in backward
    trainer.train()
  File "/home/notebook/code/personal/80370039/lzl_musicml/lzl_code/audiolm_pytorch/trainer.py", line 416, in train
    torch.autograd.backward(
  File "/opt/conda/lib/python3.8/site-packages/torch-1.13.1-py3.8-linux-x86_64.egg/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 220 has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration. You can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print parameter names for further debugging.
    logs = self.train_step()
  File "/home/notebook/code/personal/80370039/lzl_musicml/lzl_code/audiolm_pytorch/trainer.py", line 348, in train_step
    self.accelerator.backward(discr_loss / self.grad_accum_every, retain_graph = True)
  File "/opt/conda/lib/python3.8/site-packages/accelerate-0.16.0-py3.8.egg/accelerate/accelerator.py", line 1441, in backward
    loss.backward(**kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch-1.13.1-py3.8-linux-x86_64.egg/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/opt/conda/lib/python3.8/site-packages/torch-1.13.1-py3.8-linux-x86_64.egg/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 220 has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration. You can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print parameter names for further debugging.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 472255) of binary: /opt/conda/bin/python

**Comment by lucidrains** [comment]
@lzl1456 oh shoot, made a few fixes in 0.12.5, let me know what you see this time

**Comment by lzl1456** [comment]
wu ,its ok ,ready to work  ，Thank you so much,  only a few warning remain！ Not sure if it affects

training with dataset of 267178 samples and validating with randomly splitted 14063 samples                                                                                                            
[W reducer.cpp:1298] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[W reducer.cpp:1298] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
0: soundstream total loss: 400785.934, soundstream recon loss: 0.411 | discr (scale 1) loss: 2.000 | discr (scale 0.5) loss: 2.000 | discr (scale 0.25) loss: 2.001
0: saving to results_960h/soundstream_results_24k
0: saving model to results_960h/soundstream_results_24k
1: soundstream total loss: 588023.516, soundstream recon loss: 0.554 | discr (scale 1) loss: 1.982 | discr (scale 0.5) loss: 1.981 | discr (scale 0.25) loss: 1.971
2: soundstream total loss: 465313.410, soundstream recon loss: 0.444 | discr (scale 1) loss: 1.986 | discr (scale 0.5) loss: 1.979 | discr (scale 0.25) loss: 1.965
3: soundstream total loss: 158263.525, soundstream recon loss: 0.159 | discr (scale 1) loss: 1.979 | discr (scale 0.5) loss: 1.976 | discr (scale 0.25) loss: 1.962
4: soundstream total loss: 80640.829, soundstream recon loss: 0.077 | discr (scale 1) loss: 1.984 | discr (scale 0.5) loss: 1.977 | discr (scale 0.25) loss: 1.965
5: soundstream total loss: 47767.637, soundstream recon loss: 0.047 | discr (scale 1) loss: 1.966 | discr (scale 0.5) loss: 1.952 | discr (scale 0.25) loss: 1.946
6: soundstream total loss: 69041.391, soundstream recon loss: 0.071 | discr (scale 1) loss: 1.957 | discr (scale 0.5) loss: 1.937 | discr (scale 0.25) loss: 1.940
7: soundstream total loss: 61881.544, soundstream recon loss: 0.060 | discr (scale 1) loss: 1.955 | discr (scale 0.5) loss: 1.940 | discr (scale 0.25) loss: 1.873
8: soundstream total loss: 24614.655, soundstream recon loss: 0.024 | discr (scale 1) loss: 1.877 | discr (scale 0.5) loss: 1.784 | discr (scale 0.25) loss: 1.862
