### ISSUE TITLE
How can I Increase Length of SoundStream Output?

### ISSUE THREAD

**Issue by adamfils2** [lucidrains/audiolm-pytorch#98]
I need to increase the length to 10 secs.

**Comment by adamfils2** [comment]
Awesome next question
How can I run only inference on the SoundStream Model without the trainer?

**Comment by lucidrains** [comment]
@adamfils2 @smcio  added a more friendly keyword argument `data_max_length_seconds`

let me know if that helps!

**Comment by adamfils** [comment]
Awesome.
Can you please tell me how to run inference on the Soundstream trained model without using the trainer class? @lucidrains

**Comment by adamfils** [comment]
Also what is the difference between sampl.flac and sample.ema.flac?

**Comment by lucidrains** [comment]
@adamfils so the customary practice when training generative model is to keep a version of the model that is exponentially moving averaged throughout training. this increases the quality of the final model (the "ema" version)

**Comment by lucidrains** [comment]
@adamfils i've added an example in the readme - try with 0.15.2 as well, to not have to worry about batch dimension

```python
audio = torch.randn(10080).cuda()
recons = soundstream(audio, return_recons_only = True) # (1, 10080) - 1 channel
```

**Comment by alexdemartos** [comment]
Does `data_max_length` affect model inference, or it can generalize to longer sequences? I'm experiencing an strange behaviour when synthesizing samples longer than `data_max_length` (i.e. the audio quality after the first `data_max_length` drops significantly, or even loud click noise appear after ~1s):

Sample 1: https://www.whyp.it/tracks/74512/sample1-750k?token=V2HmS
Sample 2: https://www.whyp.it/tracks/74514/sample2-750k?token=Tmlcn

All generated samples suffer from this loud noise at the same spot.

**Comment by boringtaskai** [comment]
How do you calculate the ideal parameter for batch_size, grad_accum_every, data_max_length,  num_train_steps?
Let say If I have 100 samples audio speech?
